x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo
  - D:/gtihubApp/moneyprinterTurbo/models:/MoneyPrinterTurbo/models
  - D:/gtihubApp/moneyprinterTurbo/mpt/storage:/MoneyPrinterTurbo/storage

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "moneyprinterturbo-webui"
    ports:
      - "8501:8501"
    command: [ "streamlit", "run", "./webui/Main.py","--browser.serverAddress=127.0.0.1","--server.enableCORS=True","--browser.gatherUsageStats=False" ]
    volumes: *common-volumes
    environment:
      - VIDEO_CODEC=libx264
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "moneyprinterturbo-api"
    ports:
      - "8080:8080"
    command: [ "python3", "main.py" ]
    volumes: *common-volumes
    environment:
      - VIDEO_CODEC=libx264
    restart: always